name = "enclosure-concepts-site"
main = "src/worker.js"
compatibility_date = "2025-08-01"
workers_dev = true
# account_id injected by deploy.sh

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "404-page"
html_handling = "none"
